-- Init database for Detail Service

CREATE DATABASE ds;
CREATE USER ds WITH ENCRYPTED PASSWORD 'ds';
GRANT ALL PRIVILEGES ON DATABASE ds TO ds;

-- Init database for Profile Service

CREATE DATABASE ps;
CREATE USER ps WITH ENCRYPTED PASSWORD 'ps';
GRANT ALL PRIVILEGES ON DATABASE ps TO ps;
